### ISSUE TITLE
.jshintrc not recognized in latest version and Brackets 34

### ISSUE THREAD

**Issue by damacster** [cfjedimaster/brackets-jshint#20]
hi, i have a .jshintrc in the project's root directory but it doesn't appear to get picked up by the extension.

i'm using Brackets 34 and the latest version of the extension (2.0.14).

if there's anything i can do to troubleshoot the issue, do let me know.

**Comment by jetand** [comment]
I also had this problem and it turned out the problem was that it does not read contents of the .jshintrc file if it does not have UTF-8 BOM (byte order mark). It opened the file which I confirmed by using Process Monitor but failed to read the settings from the file. Brackets showed no errors and no warnings about this. It just failed silently. You can set the encoding in for example Notepad++. Make sure you delete all invalid UTF-8 from the file.
![encoding](https://cloud.githubusercontent.com/assets/6572543/12675043/44b8e7aa-c690-11e5-9940-b7b9e1bc31d2.png)

**Comment by erik-slack** [comment]
I'm having issues with brackets not applying my .jshintrc file.  It's in my project's root and if I use a per-file directive then it recognizes that in jshint, but for some reason I can't get it to detect the .jshintrc whether I put it in the root of the project or in the folder with the file I'm looking at.

Can anyone help me get this to work?

**Comment by cfjedimaster** [comment]
If you open up the dev console, do you see any errors perhaps?

**Comment by erik-slack** [comment]
![capture2](https://cloud.githubusercontent.com/assets/8229820/13192230/ec02b8fa-d726-11e5-8d54-be8a80459a27.JPG)
![capture](https://cloud.githubusercontent.com/assets/8229820/13192232/ed72a7cc-d726-11e5-8658-118ab89cc20d.JPG)

**Comment by cfjedimaster** [comment]
No worries.
